[package]
name = "eldritchwire"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
eldritchwire_macros = { path = "../eldritchwire_macros" }

[features]
"default" = ["bounds-checked"]
"bounds-checked" = []
