name: GitHub Release on Tag

on:
  push:
    tags:
      - 'v*'   # trigger on tags like v1.0.0

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Extract changelog entry
        id: changelog
        run: |
          version="${{ steps.get_version.outputs.version }}"
          awk "/^## \\[?$version\\]?/,/^## /" CHANGELOG.md | \
          sed '$d' > RELEASE_NOTES.md || true

          # If no section was found, fall back to entire changelog
          if [ ! -s RELEASE_NOTES.md ]; then
            cp CHANGELOG.md RELEASE_NOTES.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ steps.get_version.outputs.version }}"
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

