name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features mock-i2c
    - name: Format Check
      run: cargo fmt --check

  build-raspberry-pi:
    runs-on: ubuntu-latest

    steps:
    - uses: mlugg/setup-zig@v2
    - uses: actions/checkout@v4
    - name: Add rustup target
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Install zigbuild
      run: cargo install cargo-zigbuild
    - name: build
      run: cargo zigbuild --target aarch64-unknown-linux-gnu --release --no-default-features --features rppal
